### Create Department
POST http://localhost:3000/departments.json
Content-Type: application/json

{
  "department_name": "test department",
  "department_manager": "test manager"
}

### Update Department
PATCH http://localhost:3000/departments/6.json
Content-Type: application/json

{
  "department_name": "update name"
}

### Delete Department
DELETE http://localhost:3000/departments/6.json

### Create Product Class
POST http://localhost:3000/productclasses.json
Content-Type: application/json

{
  "product_class_name": "test product class",
  "product_class_code": "TEST"
}

### Update Product Class
PATCH http://localhost:3000/productclasses/6.json
Content-Type: application/json

{
  "product_class_name": "update test product class"
}

### Delete Product Class
DELETE http://localhost:3000/productclasses/7.json


### Create Product
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "product_name": "test name",
  "product_code": "test",
  "product_description": "test description",
  "productclass_id": 1
}

### Update Product
PATCH http://localhost:3000/products/6.json
Content-Type: application/json

{
  "product_name": "update test name"
}

### Delete Product
DELETE http://localhost:3000/products/6.json

### Create Root Cause
POST http://localhost:3000/rootcauses.json
Content-Type: application/json

{
  "product_id": 1,
  "issue_description": "test",
  "severity": "High",
  "department_id": 4,
  "root_cause_analysis": "test"
}

### Update Root Cause
PATCH http://localhost:3000/rootcauses/7.json
Content-Type: application/json

{
  "issue_description": "update test"
}

### Delete Product
DELETE http://localhost:3000/rootcauses/7.json